openapi: 3.0.1
info:
  title: Clientes
  description: 'Este servicio obtiene datos de Clientes'
  contact:
    name: Cecilia Godoy
    email: cecilia.godoy@familiar.com.py
  version: 1.0.0
servers:
  - url: https://localhost/clientes
paths:
  '/listar/{codigo-cliente}':
    get:
      tags:
        - clientes
      summary: clientes
      description: clientes
      operationId: listar
      parameters:
        - $ref: './familiar-components.yaml#/components/parameters/codigo-cliente'
      responses:
        '200':
          $ref: './familiar-components.yaml#/components/responses/Cuenta'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'
    