openapi: 3.0.1
info:
  title: Cuentas
  description: 'Este servicio obtiene datos de las Cuentas de un cliente'
  contact:
    name: Cecilia Godoy
    email: cecilia.godoy@familiar.com.py
  version: 1.0.0
servers:
  - url: https://localhost/cuentas
paths:
  '/listar/{codigo-cliente}':
    get:
      tags:
        - cuentas
      summary: cuentas
      description: cuentas
      operationId: listar
      parameters:
        - $ref: './familiar-components.yaml#/components/parameters/codigo-cliente'
      responses:
        '200':
          $ref: '#/components/responses/CuentaListarResponse'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'
  '/listar/{codigo-cliente}/cuenta/{codigo-cuenta}':
    get:
      tags:
        - cuentas.
      summary: obtner una cuenta
      description: obtener una cuenta
      operationId: get
      parameters:
        - $ref: './familiar-components.yaml#/components/parameters/codigo-cliente'
        - $ref: './familiar-components.yaml#/components/parameters/codigo-cuenta'
      responses:
        '200':
          $ref: '#/components/responses/CuentaResponse'
        '400':
          $ref: './familiar-components.yaml#/components/responses/BadRequest'
        '401':
          $ref: './familiar-components.yaml#/components/responses/Unauthorized'
        '403':
          $ref: './familiar-components.yaml#/components/responses/Forbidden'
        '404':
          $ref: './familiar-components.yaml#/components/responses/NotFound'
        '429':
          $ref: './familiar-components.yaml#/components/responses/TooManyRequests'
        '500':
          $ref: './familiar-components.yaml#/components/responses/InternalServerError'

components:
  schemas:
    Cuenta:
      $ref: './familiar-components.yaml#/components/schemas/Cuenta'
    CuentaListar:
      $ref: './familiar-components.yaml#/components/schemas/CuentaListar'

  responses:
    CuentaListarResponse:
      description: Listar Cuenta
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CuentaListar'
    CuentaResponse:
      description: Cuenta
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Cuenta'
    